### ISSUE TITLE
GLIBC version not found when running examples

### ISSUE THREAD

**Issue by zjingwang** [GoogleCloudPlatform/zetasql-toolkit#13]
**failed when running AnalyzeWithoutCatlog with error below**
```
/tmp/nativeutils667648329377895/liblocal_service_jni.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/nativeutils667648329377895/liblocal_service_jni.so)
```
**java version**
```
java-14-openjdk
```
**os**
```
centos 7
```

**Comment by ppaglilla** [comment]
This is a compatibility issue from ZetaSQL itself, rather than with the toolkit. ZetaSQL is built on C++ and the Java API loads a shared library with the native code (that's the `liblocal_service_jni.so` file mentioned in the error message). The problem happens because the shared library dynamically links to a version of `glibc` which is not available by default on CentOS 7.

My recommendation would be switching to either:
* A different distribution which does not have this issue.
    * Ubuntu 20.04 is ZetaSQL's reference platform.
    * I've also personally tested Ubuntu 18.04, Ubuntu 22.04, RHEL 9.2 and CentOS 9.
* Containers
    * The `zetasql-toolkit-examples` module is prepared to be easily packaged into a container using [Jib](https://cloud.google.com/java/getting-started/jib).
    * See how to in the [README](https://github.com/GoogleCloudPlatform/zetasql-toolkit/tree/version/v0.4.0/zetasql-toolkit-examples).
    * Any application you'd like to build using the toolkit could use this same approach.

If those don't work, you may be able to add the required shared libraries to your system. But messing with `glibc` versions in a system might not be the best of ideas.
