### ISSUE TITLE
Getting the Executed line for each Resolved Statement

### ISSUE THREAD

**Issue by SDorgan** [GoogleCloudPlatform/zetasql-toolkit#16]
Currently, the Statement Iterator analyzes each statement in a Query and returns only the Resolved Statements with the respective dependency trees. I'm looking for a way to obtain both the Resolved Statements, and what statement was being executed.
Example, If my inputing Query is:
```
CREATE TABLE t1 AS (SELECT 1 AS column);
CREATE TABLE t2 AS (SELECT 1 AS column);
```

I would  like my output to look like so:
```
Next line: CREATE TABLE t1 AS (SELECT 1 AS column);
Result:
CreateTableAsSelectStmt
[etc]

Next line: CREATE TABLE t2 AS (SELECT 1 AS column);
Result:
CreateTableAsSelectStmt
[etc]
```

Is there a way to do this without manually parsing the file and inputing each statement into the ZetaSQLToolkitAnalyzer?

**Comment by ppaglilla** [comment]
Since the version of the toolkit (`0.4.0`), performing analysis returns an `Iterator` of [`AnalyzedStatement`](https://github.com/GoogleCloudPlatform/zetasql-toolkit/blob/e1a84674b88265721bbd383ea3fef2797b0318b5/zetasql-toolkit-core/src/main/java/com/google/zetasql/toolkit/AnalyzedStatement.java#L23) objects. Those currently contain the parsed statement (an `ASTStatement` object) and, when possible, the `ResolvedStatement` object.

I'll add the original query to the `AnalyzedStatement` object in the next release of the toolkit, so it will be readily available.

In the meantime, here's an example of how you can work around not having it. Parsed statements contain the location of the statement in the original query string, so you can use those to substring the original.

``` java
String query = "CREATE TEMP TABLE `t` AS (SELECT 1 AS column);\n"
    + "SELECT * FROM `t` WHERE column = 1;";

BigQueryCatalog catalog = ...;
AnalyzerOptions options = ...;
ZetaSQLToolkitAnalyzer analyzer = new ZetaSQLToolkitAnalyzer(options);

Iterator<AnalyzedStatement> statementIterator = analyzer.analyzeStatements(query, catalog);

statementIterator.forEachRemaining(analyzedStatement -> {
  // Use the parse location to get the query segment for this statement
  ASTStatement parsedStmt = analyzedStatement.getParsedStatement();
  ParseLocationRange stmtLocation = parsedStmt.getParseLocationRange();
  String querySegment = query.substring(stmtLocation.start(), stmtLocation.end());

  Optional<ResolvedStatement> maybeResolvedStmt = analyzedStatement.getResolvedStatement();

  System.out.printf("Next statement: %s\n", querySegment);
  System.out.println("Result:");
  maybeResolvedStmt.ifPresent(System.out::println);
});
```

**Comment by ppaglilla** [comment]
You're welcome! Thank you for using the tool!
