### ISSUE TITLE
zetasql-toolkit depends on concrete slf4j-simple

### ISSUE THREAD

**Issue by hamnis** [GoogleCloudPlatform/zetasql-toolkit#24]
It should either be in test-scope or optional.

for now an exclusion is needed if you use any other slf4j backend.

**Comment by ppaglilla** [comment]
Thanks for calling this out!

I removed both the `slf4j-api` and `slf4j-simple` dependencies from `zetasql-toolkit-core`, neither were required. The next release (`0.5.0`) will not include them and should be released in just a few days.

`zetasql-toolkit-bigquery` will still depend on `slf4j-api:1.7.25`, since that is a transitive dependency of the BigQuery client library.

**Comment by hamnis** [comment]
@ppaglilla any chance of getting a release which fixes this out ?

**Comment by ppaglilla** [comment]
Apologies for the delayed responses here! I'm releasing a new version with this fix in the next few days, likely as soon as we merge https://github.com/GoogleCloudPlatform/zetasql-toolkit/pull/33.
